<a href="https://colab.research.google.com/github/Prashil-14-Stack/ML/blob/main/HandwrittenImageDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [108]:
import numpy as np
import pandas as pd 
from sklearn.datasets import load_digits  # Dataset from Scikit learn load "load_digits" 

In [109]:
df=load_digits()

In [110]:
df

{'DESCR': ".. _digits_dataset:\n\nOptical recognition of handwritten digits dataset\n--------------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 5620\n    :Number of Attributes: 64\n    :Attribute Information: 8x8 image of integer pixels in the range 0..16.\n    :Missing Attribute Values: None\n    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)\n    :Date: July; 1998\n\nThis is a copy of the test set of the UCI ML hand-written digits datasets\nhttps://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits\n\nThe data set contains images of hand-written digits: 10 classes where\neach class refers to a digit.\n\nPreprocessing programs made available by NIST were used to extract\nnormalized bitmaps of handwritten digits from a preprinted form. From a\ntotal of 43 people, 30 contributed to the training set and different 13\nto the test set. 32x32 bitmaps are divided into nonoverlapping blocks of\n4x4 and the number o

In [111]:
print(df.data)
print(df.target)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]


In [112]:
print(df.images.shape)

(1797, 8, 8)


In [113]:
print(df.data.shape) #image is flattened (in numerical form), hence 64 as 8*8

(1797, 64)


In [114]:
imageLength=len(df.images)

In [115]:
print(df.target.shape)

(1797,)


In [116]:
X=df.images.reshape((imageLength,-1)) #here we are reshaping the image in matrix form to perfom actions


In [117]:
X.shape

(1797, 64)

In [118]:
Y=df.target

In [119]:
Y.shape

(1797,)

In [120]:
from sklearn.model_selection import train_test_split #Splitting into test and train dataset
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30,random_state=0)

In [121]:
from sklearn import svm


In [122]:
model=svm.SVC(kernel='linear') #SVC (Support vector classifier is the classifier used in support vector machine)

In [123]:
model.fit(X_train,y_train) #training the mdoel

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [124]:
y_pred=model.predict(X_test) #Evaluevating the model

In [125]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [126]:
acc=accuracy_score(y_test,y_pred)

In [127]:
print(acc*100)

97.4074074074074
