<a href="https://colab.research.google.com/github/Prashil-14-Stack/ML/blob/main/StockPricepredcition_SVR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [151]:
import numpy as np
import pandas as pd

In [152]:
from google.colab import files
uploaded=files.upload()

Saving data.csv to data (5).csv


In [153]:
df=pd.read_csv('data.csv')

In [154]:
X=df.iloc[:,:-1].values

In [155]:
X

array([[ 168.18181818],
       [ 187.87878788],
       [ 207.57575758],
       [ 227.27272727],
       [ 246.96969697],
       [ 266.66666667],
       [ 286.36363636],
       [ 306.06060606],
       [ 325.75757576],
       [ 345.45454545],
       [ 365.15151515],
       [ 384.84848485],
       [ 404.54545455],
       [ 424.24242424],
       [ 443.93939394],
       [ 463.63636364],
       [ 483.33333333],
       [ 503.03030303],
       [ 522.72727273],
       [ 542.42424242],
       [ 562.12121212],
       [ 581.81818182],
       [ 601.51515152],
       [ 621.21212121],
       [ 640.90909091],
       [ 660.60606061],
       [ 680.3030303 ],
       [ 700.        ],
       [ 719.6969697 ],
       [ 739.39393939],
       [ 759.09090909],
       [ 778.78787879],
       [ 798.48484848],
       [ 818.18181818],
       [ 837.87878788],
       [ 857.57575758],
       [ 877.27272727],
       [ 896.96969697],
       [ 916.66666667],
       [ 936.36363636],
       [ 956.06060606],
       [ 975.757

In [156]:
X.reshape(-1,1)

array([[ 168.18181818],
       [ 187.87878788],
       [ 207.57575758],
       [ 227.27272727],
       [ 246.96969697],
       [ 266.66666667],
       [ 286.36363636],
       [ 306.06060606],
       [ 325.75757576],
       [ 345.45454545],
       [ 365.15151515],
       [ 384.84848485],
       [ 404.54545455],
       [ 424.24242424],
       [ 443.93939394],
       [ 463.63636364],
       [ 483.33333333],
       [ 503.03030303],
       [ 522.72727273],
       [ 542.42424242],
       [ 562.12121212],
       [ 581.81818182],
       [ 601.51515152],
       [ 621.21212121],
       [ 640.90909091],
       [ 660.60606061],
       [ 680.3030303 ],
       [ 700.        ],
       [ 719.6969697 ],
       [ 739.39393939],
       [ 759.09090909],
       [ 778.78787879],
       [ 798.48484848],
       [ 818.18181818],
       [ 837.87878788],
       [ 857.57575758],
       [ 877.27272727],
       [ 896.96969697],
       [ 916.66666667],
       [ 936.36363636],
       [ 956.06060606],
       [ 975.757

In [157]:
Y=df.iloc[:,-1].values

In [158]:
Y

array([160.84024381, 159.41365734, 157.1368088 , 159.35784736,
       157.54286158, 157.73520716, 159.34756091, 155.23404557,
       155.80774009, 158.3299704 , 157.62585291, 160.47697951,
       158.22940639, 157.41781684, 163.37069148, 160.18481104,
       160.96838974, 158.18080666, 160.13850728, 161.6460876 ,
       159.31922497, 162.56957785, 160.81387414, 161.62873371,
       161.20567768, 166.31061698, 162.77603585, 160.88457814,
       164.84205952, 160.95225209, 164.00863628, 159.86853854,
       161.32847639, 164.57554065, 165.85572104, 164.91849414,
       164.54143071, 164.36748958, 162.20962269, 163.92394795,
       164.63932852, 167.87182021, 166.64178203, 162.62543484,
       166.99665279, 165.77528998, 165.38858024, 168.16274652,
       169.19836268, 169.19589357, 165.85186798, 167.10884798,
       168.58676929, 170.07230238, 167.35983334, 168.14383356,
       166.49945126, 166.51667766, 170.73111225, 172.01551036,
       169.35597976, 171.70403549, 170.61721144, 168.80

In [174]:
from sklearn.model_selection import train_test_split

In [175]:
(X_train,X_test, y_train, y_test)=train_test_split(X,Y,test_size=0.20,random_state=0)

In [178]:
y_test.shape

(19,)

In [179]:
X_test.shape

(19, 1)

In [180]:
y_train.shape

(75,)

In [181]:
X_train.shape

(75, 1)

In [182]:
X_train = X_train.reshape(-1, 1)
X_test = X_test.reshape(-1, 1)

In [183]:
from sklearn.svm import SVR

In [184]:
model=SVR()

In [185]:
model.fit(X,Y)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [186]:
y_pred=model.predict(X_test)

In [187]:
from sklearn.metrics import r2_score




In [188]:
rsqre=r2_score(y_test,y_pred)

In [189]:
print("R-Square :", rsqre*100)

R-Square : 88.92203835883006
